### ISSUE TITLE
Fastlane directory uses invalid names for some locales

### ISSUE THREAD

**Issue by bene64** [SubhamTyagi/android-ocr#24]
[Fastlane](https://github.com/fastlane/fastlane/blob/633860a5aae0fa9c0b936797560efb24181b1bf7/fastlane_core/lib/fastlane_core/languages.rb#L14) uses [BCP47](https://www.w3.org/International/articles/bcp47/) locale tags, which use a `-` as the separator rather than `_`. There are a number of locales that use the `_` here. Please rename those dirs to use `-`. Thanks!

For reference: F-Droid downstream [issue](https://gitlab.com/fdroid/fdroiddata/-/issues/2323).

**Comment by SubhamTyagi** [comment]
Translation is done via Weblate and These directories also created by Weblate.  It seems that this issue is related to Weblate `App store meta data files` file format. I can also change the directory name but when someone adds new language then it will fails hence You should also create a issue there.

**Comment by bene64** [comment]
Thanks for that hint, we'll have a look into it.

**Comment by eighthave** [comment]
There is an issue filed for Weblate here https://github.com/WeblateOrg/weblate/issues/5522.  Weblate's part in this was using the wrong separator, that's fixed.  As for choosing the right locale tags for Google Play, that's currently up to the app dev, or Fastlane if you use that, since Google Play has strange rules and changes them sometimes.  F-Droid will use any valid BCP47 locale tag.

**Comment by SubhamTyagi** [comment]
> Weblate's part in this was using the wrong separator, that's fixed.

So I have to rename that language directory (Currently only one 😃 )
